version: 2.1

commands:
  qlty-coverage-publish:
    steps:
      - run:
          name: Install Qlty CLI
          command: curl https://qlty.sh | sh
      - run:
          name: Upload coverage to Qlty
          command: ~/.local/bin/qlty coverage publish build/logs/clover.xml
  install-dependencies:
    parameters:
      xdebug_version:
        type: string
    steps:
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Install xdebug
          command: sudo -E install-php-extensions xdebug-<< parameters.xdebug_version >>
      - run:
          name: Enable xdebug
          command: sudo -E docker-php-ext-enable xdebug
  build:
    steps:
      - run:
          name: Check coding style (PSR12)
          command: make phpcs
      - run:
          name: Run unit tests
          command: make phpunit-coverage

jobs:
  build:
    parameters:
      php_version:
        type: string
      xdebug_version:
        type: string
    docker:
      - image: cimg/php:<< parameters.php_version >>
    resource_class: small
    steps:
      - checkout
      - install-dependencies:
          xdebug_version: << parameters.xdebug_version >>
      - build
      - when:
          condition:
            equal: ["8.5", << parameters.php_version >>]
          steps:
            - qlty-coverage-publish

workflows:
  ci:
    jobs:
      - build:
          name: build-php-<< matrix.php_version >>
          matrix:
            parameters:
              php_version: ["8.2", "8.3", "8.4", "8.5"]
              xdebug_version: ["stable"]
