<?php

namespace NumberToWords\NumberTransformer;

class FrenchBelgianNumberTransformerTest extends NumberTransformerTest
{
    protected function setUp(): void
    {
        $this->numberTransformer = new FrenchBelgianNumberTransformer();
    }

    public function providerItConvertsNumbersToWords(): array
    {
        return [
            [-1104, 'moins mille cent quatre'],
            [0, 'zéro'],
            [1, 'un'],
            [2, 'deux'],
            [3, 'trois'],
            [4, 'quatre'],
            [5, 'cinq'],
            [6, 'six'],
            [7, 'sept'],
            [8, 'huit'],
            [9, 'neuf'],
            [11, 'onze'],
            [12, 'douze'],
            [16, 'seize'],
            [19, 'dix-neuf'],
            [20, 'vingt'],
            [21, 'vingt et un'],
            [26, 'vingt-six'],
            [30, 'trente'],
            [31, 'trente et un'],
            [40, 'quarante'],
            [43, 'quarante-trois'],
            [50, 'cinquante'],
            [55, 'cinquante-cinq'],
            [60, 'soixante'],
            [67, 'soixante-sept'],
            [70, 'septante'],
            [71, 'septante et un'],
            [79, 'septante-neuf'],
            [80, 'quatre-vingts'],
            [81, 'quatre-vingt-un'],
            [91, 'nonante et un'],
            [100, 'cent'],
            [101, 'cent un'],
            [199, 'cent nonante-neuf'],
            [203, 'deux cent trois'],
            [287, 'deux cent quatre-vingt-sept'],
            [300, 'trois cents'],
            [356, 'trois cent cinquante-six'],
            [410, 'quatre cent dix'],
            [434, 'quatre cent trente-quatre'],
            [578, 'cinq cent septante-huit'],
            [689, 'six cent quatre-vingt-neuf'],
            [729, 'sept cent vingt-neuf'],
            [894, 'huit cent nonante-quatre'],
            [999, 'neuf cent nonante-neuf'],
            [1000, 'mille'],
            [1001, 'mille un'],
            [1097, 'mille nonante-sept'],
            [1104, 'mille cent quatre'],
            [1243, 'mille deux cent quarante-trois'],
            [2385, 'deux mille trois cent quatre-vingt-cinq'],
            [3766, 'trois mille sept cent soixante-six'],
            [4196, 'quatre mille cent nonante-six'],
            [5846, 'cinq mille huit cent quarante-six'],
            [6459, 'six mille quatre cent cinquante-neuf'],
            [7232, 'sept mille deux cent trente-deux'],
            [8569, 'huit mille cinq cent soixante-neuf'],
            [9539, 'neuf mille cinq cent trente-neuf'],
            [11000, 'onze mille'],
            [11001, 'onze mille un'],
            [21000, 'vingt et un mille'],
            [21512, 'vingt et un mille cinq cent douze'],
            [90000, 'nonante mille'],
            [92100, 'nonante-deux mille cent'],
            [212112, 'deux cent douze mille cent douze'],
            [720018, 'sept cent vingt mille dix-huit'],
            [999000, 'neuf cent nonante-neuf mille'],
            [999999, 'neuf cent nonante-neuf mille neuf cent nonante-neuf'],
            [1000000, 'un million'],
            [1001001, 'un million mille un'],
            [2000000, 'deux millions'],
            [3248518, 'trois millions deux cent quarante-huit mille cinq cent dix-huit'],
            [4000000, 'quatre millions'],
            [5000000, 'cinq millions'],
            [999000000, 'neuf cent nonante-neuf millions'],
            [999000999, 'neuf cent nonante-neuf millions neuf cent nonante-neuf'],
            [999999000, 'neuf cent nonante-neuf millions neuf cent nonante-neuf mille'],
            [999999999, 'neuf cent nonante-neuf millions neuf cent nonante-neuf mille neuf cent nonante-neuf'],
            [1174315110, 'un milliard cent septante-quatre millions trois cent quinze mille cent dix'],
            [1174315119, 'un milliard cent septante-quatre millions trois cent quinze mille cent dix-neuf'],
            [1800000006, 'un milliard huit cents millions six'],
            [15174315119, 'quinze milliards cent septante-quatre millions trois cent quinze mille cent dix-neuf'],
            [35174315119, 'trente-cinq milliards cent septante-quatre millions trois cent quinze mille cent dix-neuf'],
            [935174315119, 'neuf cent trente-cinq milliards cent septante-quatre millions trois cent quinze mille cent dix-neuf'],
            [2935174315119, 'deux billions neuf cent trente-cinq milliards cent septante-quatre millions trois cent quinze mille cent dix-neuf'],
            [79797979797979797, 'septante-neuf billiards sept cent nonante-sept billions neuf cent septante-neuf milliards sept cent nonante-sept millions neuf cent septante-neuf mille sept cent nonante-sept'],
        ];
    }
}
